version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - ls -la 
      - sam package --template-file template.yml --s3-bucket codepipeline-us-east-1-202783545158 --output-template-file packaged-template.yml --debug
artifacts:
  files:
    - packaged-template.yml
