version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - sam package --template-file template.yml 
                    --s3-bucket case4632943791 
                    --output-template-file packaged-template.yml 

      - sam deploy  --template-file packaged-template.yml 
                    --s3-bucket case4632943791 
                    --stack-name mystack 
                    --no-fail-on-empty-changeset 
                    --capabilities CAPABILITY_IAM 
                    --no-confirm-changeset
artifacts:
  files:
    - packaged-template.yml
