version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "autopub"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-izf808rgeven"
s3_prefix = "autopub"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = ["InstanceTypeParameter"="m2.small"]